name: dxlibv3_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  pinenacl: ^0.6.0
  cryptography: ^2.7.0
  http: ^1.2.2
  crypto: ^3.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
